[package]
name = "mcl_sched"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmcl-sys = {version = "0.1.1", path = "../libmcl-sys"}
clap = {version = "4.0.29", features = ["derive"] }
